"""empty message

Revision ID: 72644b38020f
Revises: b333c149366f
Create Date: 2024-01-28 14:50:27.590567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72644b38020f'
down_revision = 'b333c149366f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('banner', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.drop_column('banner')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
