"""empty message

Revision ID: 80c1d9895a1b
Revises: 11752a18b8bb
Create Date: 2024-01-25 23:28:59.602878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c1d9895a1b'
down_revision = '11752a18b8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mangoid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mangoidwallet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')
        batch_op.drop_column('mangoidwallet')
        batch_op.drop_column('mangoid')

    # ### end Alembic commands ###
