"""empty message

Revision ID: b333c149366f
Revises: 80c1d9895a1b
Create Date: 2024-01-25 23:49:18.807406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b333c149366f'
down_revision = '80c1d9895a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfildone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_be', schema=None) as batch_op:
        batch_op.drop_column('perfildone')

    # ### end Alembic commands ###
