"""empty message

Revision ID: e026e6740ce5
Revises: d71bdae5457c
Create Date: 2024-01-23 09:24:13.796819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e026e6740ce5'
down_revision = 'd71bdae5457c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_urls', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('images_urls')

    # ### end Alembic commands ###
